DROP TABLE IF EXISTS Project.Workout;
DROP TABLE IF EXISTS Project.ExerciseMuscleGroup;
DROP TABLE IF EXISTS Project.Exercise;
DROP TABLE IF EXISTS Project.MuscleGroup;
DROP TABLE IF EXISTS Project.Session;
DROP TABLE IF EXISTS Project.Environment;
DROP TABLE IF EXISTS Project.Weather;
DROP TABLE IF EXISTS Project.Location;
DROP TABLE IF EXISTS Project.DailyMetrics;